<?php
    if($_SERVER["REQUEST_METHOD"] === "POST") {
        $productName = $_POST["product_name"];
        $sku = $_POST["sku"];
        $price = $_POST["price"];
        $qty = $_POST["qty"];
        if(!$controller->create($productName, $sku, $price, $qty)) {
            $error = "Hubo un error al guardar el producto";
        }

    }
?>
<!doctype html>
<html lang="es-MX">
<?php include(VIEWS_DIR . "/partials/head.phtml"); ?>
<body>
    <?php include(VIEWS_DIR . "/partials/header.phtml"); ?>
    <main class="container">
        <?php 
            if(!isset($error)) {
        ?>
            <div class="alert alert-success" role="alert">
                Producto agregado correctamente
            </div>
        <?php
            } else {
        ?>
            <div class="alert alert-danger" role="alert">
                <?php echo $error; ?>
            </div>
        <?php
            }
        ?>
        <h1>Agregar productos</h1>
        <form action="/add-products" method="POST" enctype="multipart/form-data">
            <div class="form-group">
                <label for="product_name">Nombre del producto</label>
                <input type="text"
                       class="form-control"
                       id="product_name"
                       name="product_name"
                       placeholder="Ingresa el nombre del producto" />
            </div>
            <div class="form-group">
                <label for="sku">SKU</label>
                <input type="text"
                       class="form-control"
                       id="sku"
                       name="sku"
                       placeholder="Ingresa el SKU" />
            </div>
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text">$</span>
                </div>
                <input type="text"
                       class="form-control"
                       id="price"
                       name="price"
                       placeholder="Ingresa el precio" />
                <div class="input-group-append">
                    <span class="input-group-text">.00</span>
                </div>
            </div>
            <div class="form-group">
                <label for="qty">Cantidad</label>
                <input type="number"
                       class="form-control"
                       id="qty"
                       name="qty"
                       placeholder="Ingresa la cantidad" />
            </div>
            <div class="form-group">
                <label for="photo">Imagen del producto</label>
                <input type="file"
                       name="image"
                       class="form-control-file"
                       id="photo">
            </div>
            <button type="submit" class="btn btn-primary">Registrar</button>
        </form>
    </main>
    <?php include(VIEWS_DIR . "/partials/footer.phtml"); ?>
    <?php include(VIEWS_DIR . "/partials/scripts.phtml"); ?>
</body>
</html>
